### ISSUE TITLE
Error in yarn dev

### ISSUE THREAD

**Issue by SaylaRdota** [firecmsco/firecms#692]
Using the command yarn create firecms-app with Node 18, 20, and 22, and following all the console steps, selecting my Firebase project, I encounter this issue when running yarn dev:
```
[ERROR] No matching export in "node_modules/@tiptap/pm/view/dist/index.js" for import "__serializeForClipboard"

    node_modules/@firecms/editor/dist/index.es.js:33:71:
      33 │ ...on as Decoration$1, __serializeForClipboard } from "@tiptap/pm/...
         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by fgatti675** [comment]
Hi! This is fixed in version `3.0.0-beta-12`
Just updting the dependency should work

**Comment by donlawatch** [comment]
Hi @fgatti675, I updated the following packages to `3.0.0-beta-12` but still not working.
Did I do something wrong?

![Image](https://github.com/user-attachments/assets/9a323c62-99f0-4f60-9043-cd9ef958e77b)

**Comment by fgatti675** [comment]
Hi @donlawatch that looks good. You may need to delete your lock files like `yarn.lock` or `package-lock.json` and the folder `node-modules` and try again.

**Comment by donlawatch** [comment]
@fgatti675 Okay, resolved now. Thank you 🤗

**Comment by SaylaRdota** [comment]
Same problem:

![Image](https://github.com/user-attachments/assets/ec9527ad-93e2-410c-ba79-0998521202ba)

**Comment by donlawatch** [comment]
@SaylaRdota Please use `PNPM` instead of `yarn`
